### PR TITLE
Implement OpenSSL::Random.random_bytes

### PR DESCRIPTION
**Pull request by herwinw**
Which also means this adds a hard dependency on the openssl headers to be able to compile. It would probably be nice to just skip the extension if those can't be found.

I might want to look into implementing more of OpenSSL later on, since cryptography is pretty much a requirement to do anything these days.

### CODE REVIEW

**Comment by herwinw** [comment]
This compiles on MacOS. The construction used to compile it feels like a hack, so I'm all ears if anyone has suggestions to improve it. Does `pkg-config` work on a Mac?
We're probably going to run into this with other libs as well.

**Comment by seven1m** [comment]
🤔 Hrmm, this worked on my Mac. I'll look at it again tomorrow.

**Comment by seven1m** [comment]
The shell out to homebrew makes too many assumptions. pkg-config should be able to get us the flags we need. I will look into it further.

**Comment by seven1m** [comment]
OK I’m happy with this for now. We may need some instructions in the readme for Mac users wanting to use openssl; I can do that later.

**Pull request merged**
