### PR TITLE
Memoize label of a compiler instruction

### PR DESCRIPTION
**Pull request by richardboehme**
This reduces transformation time by ~50%

Before:
image

After:
image

With label as class method:

image

### CODE REVIEW

**Comment by richardboehme** [comment]
Now that I've took another look at the profile. Couldn't `BaseInstruction#label` be a class method? This would speed this up a bit more...

**Comment by seven1m** [comment]
Yeah probably could be a class method. Try it and see!

**Comment by richardboehme** [comment]
> Yeah probably could be a class method. Try it and see!

This got us another ~100ms when compiling the numeric step spec!

**Comment by seven1m** [comment]
Wow it's amazing what one little change can do!

**Pull request merged**
