### PR TITLE
Implement Rational#truncate

### PR DESCRIPTION
**Pull request by herwinw**

### CODE REVIEW

**Review by seven1m — COMMENTED** [review]
Do we need to check for divide-by-zero?

**Comment by herwinw** [comment]
It turns out we do, but not in this change.

In IRB:
```
irb(main):001:0> Rational(1, 0)
(irb):1:in `Rational': divided by 0 (ZeroDivisionError)
```
But in Natalie:
```
nat> Rational(1, 0)
(1/0)
```
I'm kind of surprised that this is not covered in the specs.

And in this change, we might want to add an explicit check for the argument being zero, which now kind of works with the long way around.

**Comment by herwinw** [comment]
I added https://github.com/ruby/spec/pull/1002 as an upstream PR to extend the specs of this method.

**Comment by herwinw** [comment]
The upstream PR has been accepted, I included the updated spec in this PR. We're fully compliant with MRI.

**Pull request merged**
