### PR TITLE
Fixes for EncodingObject

### PR DESCRIPTION
**Pull request by nanobowers**
+ Add `Encoding.locale_charmap`
+ Add `Encoding.dummy?`.  None of our active encodings are dummies, so this is not yet fully testable.
+ Fix `Encoding.find` to support special lookups for "internal", "external", "filesystem" and "locale"
+ Add support for getting/setting default_external, locale and filesystem encodings, with a static initializer.  Unclear at this point how OS dependent this is for the platforms Natalie supports.

### CODE REVIEW

**Comment by nanobowers** [comment]
Adding a help-wanted in case anyone is available to help debug the macos fail.
Otherwise will need to chop this PR into tiny bits and submit them individually so the CI can run and hopefully isolate the issue.

**Comment by seven1m** [comment]
I'll take a look! 👀

**Comment by seven1m** [comment]
FWIW, I cannot get this spec to fail on my Mac. Still looking though!

**Comment by seven1m** [comment]
I was able to reproduce this by running the tests in a specific order with:

```sh
ruby test/all.rb --seed 29544
```

Then I tracked down the issue to `isprint()` on [this line](https://github.com/nanobowers/natalie/blob/encoding_20230116/src/array_packer/string_handler.cpp#L195) returning true (1) for values in the 159 and higher range.

I suspect some prior test is changing a locale which is causing `isprint()` to have different behavior later on? That's the only thing I can think of.

I know on some old IBM systems, those higher `char` values are box/border printing characters, but I don't know what would be switching Mac into that locale.

Anyway, I fixed it by adding another conditional on to check that the character value is octal 0176 or lower, which is what `man isprint` indicates is the highest printable character:

```
     In the ASCII character set, this includes the following characters (preceded by their numeric values, in octal):

     040 sp 041 ``!'' 042 ``"'' 043 ``#'' 044 ``$''
     045 ``%'' 046 ``&'' 047 ``''' 050 ``('' 051 ``)''
     052 ``*'' 053 ``+'' 054 ``,'' 055 ``-'' 056 ``.''
     057 ``/'' 060 ``0'' 061 ``1'' 062 ``2'' 063 ``3''
     064 ``4'' 065 ``5'' 066 ``6'' 067 ``7'' 070 ``8''
     071 ``9'' 072 ``:'' 073 ``;'' 074 ``<'' 075 ``=''
     076 ``>'' 077 ``?'' 100 ``@'' 101 ``A'' 102 ``B''
     103 ``C'' 104 ``D'' 105 ``E'' 106 ``F'' 107 ``G''
     110 ``H'' 111 ``I'' 112 ``J'' 113 ``K'' 114 ``L''
     115 ``M'' 116 ``N'' 117 ``O'' 120 ``P'' 121 ``Q''
     122 ``R'' 123 ``S'' 124 ``T'' 125 ``U'' 126 ``V''
     127 ``W'' 130 ``X'' 131 ``Y'' 132 ``Z'' 133 ``[''
     134 ``\'' 135 ``]'' 136 ``^'' 137 ``_'' 140 ```''
     141 ``a'' 142 ``b'' 143 ``c'' 144 ``d'' 145 ``e''
     146 ``f'' 147 ``g'' 150 ``h'' 151 ``i'' 152 ``j''
     153 ``k'' 154 ``l'' 155 ``m'' 156 ``n'' 157 ``o''
     160 ``p'' 161 ``q'' 162 ``r'' 163 ``s'' 164 ``t''
     165 ``u'' 166 ``v'' 167 ``w'' 170 ``x'' 171 ``y''
     172 ``z'' 173 ``{'' 174 ``|'' 175 ``}'' 176 ``~''
```

**Comment by nanobowers** [comment]
@seven1m   Thanks for figuring that out, that's some impressive sleuthing!

**Pull request merged**
