### PR TITLE
Convert flags_struct into a real object

### LINKED ISSUE #1247: Cleanup of construction of flags_struct
Right now, this struct has a very simple constructor, which defers most of the work to a bunch of parser methods in an anonymous namespace. This could be rewritten to some private methods on the struct (or class).

(Related case: #1225)

### PR DESCRIPTION
**Pull request by herwinw**
This closes #1247 

This is one of those chores that had to be done some day, and it was getting a bit into the way of #1395.

### CODE REVIEW

**Comment by herwinw** [comment]
Note to self: make `flags_struct` a subclass of `Cell` and implement the GC visitor. And I think the gc_lint check should checks structs as well.

**Comment by seven1m** [comment]
If we don't attach a `flags_struct` to another object, then I don't think we need to make it managed by the GC do we? Is there a case where `flags_struct` will live longer than a single call frame?

**Comment by herwinw** [comment]
Probably not (although I'm not sure when the GC kicks in, I assume only when we leave a scope / pop an env).

I tried to exclude this class, but that still failed and I don't really know why. It doesn't really help that I run Clang 16 on my machine, which seems to break the gc_lint script, so I cannot run it locally.
If anybody else wants to have a try: just convert `flags_struct` to a class and put `public:` as the first line.

**Comment by seven1m** [comment]
Sorry I didn't have time to look at this. If you want to ship this as-is and make a new issue, I can circle back to the struct/class thing later. I don't think it's a big hangup for me that it is a `struct` for now.

**Comment by herwinw** [comment]
I'm only like 30% finished, so I don't wan to ship it as it is now :wink:

**Comment by herwinw** [comment]
And this should fix the remaining 70%. I'll leave the conversion to a class and the changes to gc_lint as an exercise to the reader.

**Review by seven1m — APPROVED** [review]
:clap:

**Pull request merged**
