### PR TITLE
Make `defined?` spec compliant

### PR DESCRIPTION
**Pull request by richardboehme**
There are probably lots of cases where this still fails and that the specs don't cover. Also I noticed an interesting bug with global regexp matches which is why we will have some NATFIXMEs in the spec.

### CODE REVIEW

**Comment by herwinw** [comment]
I tried this one with the script of #1734, there are still some issues with the const-missing logic. This might have some deeper causes, and it's not blocking for this update, so see it as a FYI.

**Comment by richardboehme** [comment]
> I tried this one with the script of #1734, there are still some issues with the const-missing logic. This might have some deeper causes, and it's not blocking for this update, so see it as a FYI.

Interesting, I can have a closer look into it. All in all `defined?` behaves quite weird so I wouldn't be suprised if there are more cases like this that are not covered in the `defined_spec`

**Comment by seven1m** [comment]
The failing spec is just a few "This issue is fixed" NATFIXMEs 🎉

**Comment by herwinw** [comment]
@richardboehme I took the liberty to push an extra commit to fix those last few issues with the specs, the branch should be ready to merge now.

**Comment by richardboehme** [comment]
> @richardboehme I took the liberty to push an extra commit to fix those last few issues with the specs, the branch should be ready to merge now.

That's fine, thank you! I just haven't been at my computer yet 😅

**Pull request merged**
