### PR TITLE
Convert NATFIXME markers in Time to blocks

### PR DESCRIPTION
**Pull request by herwinw**
Another one for #963

### CODE REVIEW

**Comment by herwinw** [comment]
```
Progress: |=======================..........*natalie20230814-8668-wb6c8d: /natalie/ext/tm/include/tm/string.hpp:39: TM::String::String(const char*): Assertion `str' failed.
 FAIL ruby/spec::spec/core/time/plus_spec.rb#test_0001_passes all specs (1748.55s)
        Expected #<Process::Status: pid 8667 exit 1> to be success?.
        /natalie/test/ruby/ruby_specs_test.rb:21:in `block (4 levels) in <top (required)>'

======................*natalie20230814-10508-hyxzz4: /natalie/ext/tm/include/tm/string.hpp:39: TM::String::String(const char*): Assertion `str' failed.
 FAIL ruby/spec::spec/core/time/minus_spec.rb#test_0001_passes all specs (2116.73s)
        Expected #<Process::Status: pid 10507 exit 1> to be success?.
        /natalie/test/ruby/ruby_specs_test.rb:21:in `block (4 levels) in <top (required)>'
```

That is an interesting error

**Comment by seven1m** [comment]
I can run it with gdb or lldb and hopefully figure out where we are passing null into the String constructor. 👀

**Comment by herwinw** [comment]
@seven1m  That would be most welcome, I've tried this on three different machines and I haven't been able to reproduce the issue.

**Comment by seven1m** [comment]
I could only reproduce this inside Docker, so I added a rake task to help with that. I believe 64b4f73a6f0bf73c4dde250ae328b500a00fab11 fixes the issue.

**Comment by herwinw** [comment]
That seems to work
```
TZ= bin/natalie -e 'Time.now.zone'
natalie20230815-117795-m1ng89: natalie/ext/tm/include/tm/string.hpp:39: TM::String::String(const char*): Assertion `str' failed.
```

**Pull request merged**
