### PR TITLE
Start work on a CSV#<< (append) spec and fix some bugs in our implementation

### PR DESCRIPTION
**Pull request by seven1m**
[#551]

@richardboehme let me know if this is the sort of thing you had in mind...

These were my steps:

- Write the spec while running it through MRI, until I'm satisfied the edge cases are documented.
- Update our implementation until the spec passes with Natalie.

### CODE REVIEW

**Comment by richardboehme** [comment]
That's exactly how I though about it as well. Actually I just started with the append spec myself, but you found some edge cases that I did not see yet 😅 Should we somehow "merge" our different specs we wrote?

I think the best approach is to write specifications for MRI and if we do not pass this spec we can either fix it directly or mark it as NATFIXME.

I'm not sure if we want to keep the new spec files in the `spec` directory or keep it separate for now (I thought about `test/lib/csv`)? This way we can keep it separate from the actual ruby/spec, but maybe it doesn't matter too much.

**Comment by seven1m** [comment]
> Should we somehow "merge" our different specs we wrote?

Yeah, sure. Do you just want to push commits to this PR?

>I think the best approach is to write specifications for MRI and if we do not pass this spec we can either fix it directly or mark it as NATFIXME.

Cool :+1: 

>I'm not sure if we want to keep the new spec files in the spec directory or keep it separate for now (I thought about test/lib/csv)? This way we can keep it separate from the actual ruby/spec, but maybe it doesn't matter too much.

Yeah I'm good with either. Actually `test/lib/csv` might be better.

**Comment by richardboehme** [comment]
I integrated the things I was working on. I hope the re-arrangements of the spec file are fine! There is some work to be done with encoding and field converters. I did not touch those yet because I have no idea how they work with CSV. Also we need to implement header support for CSVs.

**Comment by richardboehme** [comment]
Also writing to the CSV *should* happen in the CSV::Writer class but I did not implement this yet.

**Review by seven1m — COMMENTED** [review]
Nice! Merge whenever you want.

**Comment by richardboehme** [comment]
I'll merge this now, leaving Encoding as a fixme for later.

**Pull request merged**
