### PR TITLE
Some minor optimizations for TM::String

### PR DESCRIPTION
**Pull request by herwinw**
Mostly implementing (and using) move semantics. This can prevent some memory moves.

### CODE REVIEW

**Comment by herwinw** [comment]
I did a few tests locally with a C++ script that used the move semantics of this class, running it in Valgrind showed that there were no memory leaks in this code.

**Comment by seven1m** [comment]
What did you change to make clang-tidy happy?

**Comment by herwinw** [comment]
Line 336 has been added:
```c++
String &operator=(String &&other) {
    delete[] m_str;
```
It's what happens when you call the following code:
```c++
TM::String str1("foo");
TM::String str2("bar");
str1 = std::move(str2);
```
In that case, you first want to free the memory of `str1.m_str`, before you copy the pointer of `str2.m_str`. So clang-tidy was correct, but the output was very confusing (it pointed at the copy of `m_length`)

**Comment by seven1m** [comment]
OK cool. Yeah I was super confused by the clang-tidy error. 😅

**Pull request merged**
